#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_TIMEOUT 500U // milliseconds


#define WS2812_DI_PIN GP21
#define AUDIO_PIN GP10
#define AUDIO_PWM_DRIVER PWMD5
#define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_A
#define AUDIO_INIT_DELAY

#ifdef AUDIO_ENABLE
    #define TEMPO_DEFAULT 140
    #define THE_SONG \
        Q__NOTE(_F3), Q__NOTE(_F4), Q__NOTE(_F3), Q__NOTE(_DS4), \
        Q__NOTE(_F3), Q__NOTE(_CS4), Q__NOTE(_F3), Q__NOTE(_C4), \
        Q__NOTE(_F3), Q__NOTE(_CS4), Q__NOTE(_F3), Q__NOTE(_C4), \
        Q__NOTE(_F3), Q__NOTE(_AS3), Q__NOTE(_F3), Q__NOTE(_C4), \
        Q__NOTE(_F3), Q__NOTE(_CS4), Q__NOTE(_F3), Q__NOTE(_DS4), \
        Q__NOTE(_F3), Q__NOTE(_CS4), Q__NOTE(_F3), Q__NOTE(_C4), \
        Q__NOTE(_F3), Q__NOTE(_GS3), Q__NOTE(_F3), Q__NOTE(_C4), \
        Q__NOTE(_F3), Q__NOTE(_AS3), H__NOTE(_F3)
    #define STARTUP_SONG SONG(THE_SONG)
#endif

#define RGBLIGHT_EFFECT_RAINBOW_MOOD

#define RGBLIGHT_LED_COUNT 1
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_MOOD
#define RGBLIGHT_DEFAULT_HUE 170
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 120
#define RGBLIGHT_LIMIT_VAL 150


#define PS2_DATA_PIN GP28
#define PS2_CLOCK_PIN GP29
#define PS2_MOUSE_SCROLL_BTN_MASK 0
// #define PS2_PIO_USE_PIO1
#define PS2_AUTO_BUTTONS_TIMEOUT 750
#define PS2_MOUSE_USE_REMOTE_MODE