BOOTMAGIC_ENABLE = yes
RGBLIGHT_ENABLE = yes
AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware
KEY_OVERRIDE_ENABLE = yes

WS2812_DRIVER_REQUIRED = yes
WS2812_DRIVER = vendor

PS2_ENABLE = yes
PS2_MOUSE_ENABLE = yes
PS2_DRIVER = vendor

MOUSEKEY_ENABLE = yes   