// Copyright 2026 Jens Nomtak
// SPDX-License-Identifier: GPL-2.0-or-later

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_TIMEOUT 500U // milliseconds

#define EECONFIG_USER_DATA_SIZE 8192
#define EECONFIG_USER_DATA_VERSION 41

#define JOYSTICK_BUTTON_COUNT 16
// Min 0, max 6: X, Y, Z, Rx, Ry, Rz
#define JOYSTICK_AXIS_COUNT 6
// Min 8, max 16
#define JOYSTICK_AXIS_RESOLUTION 10
// #define JOYSTICK_INTERFACE_NAME "Derail Control Primary"

#define JOYSTICK2_AXIS_COUNT 6
#define JOYSTICK2_AXIS_RESOLUTION 10
#define JOYSTICK2_BUTTON_COUNT 16
#define JOYSTICK2_INTERFACE_NAME "Derail Control Secondary"

#define RGBLIGHT_EFFECT_RAINBOW_MOOD

#define WS2812_DI_PIN GP16   // change to your actual data pin
#define RGBLIGHT_LED_COUNT 5
#define WS2812_RGBW
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_MOOD
