BOOTMAGIC_ENABLE = yes
JOYSTICK_ENABLE = yes
JOYSTICK_SHARED_EP = yes
JOYSTICK2_ENABLE = yes
VIRTSER_ENABLE = yes

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812

WS2812_DRIVER_REQUIRED = yes
WS2812_DRIVER = vendor