// Copyright 2026 Jens Nomtak
// SPDX-License-Identifier: GPL-2.0-or-later

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_TIMEOUT 500U // milliseconds

#define WS2812_DI_PIN GP16

#define RGBLIGHT_EFFECT_RAINBOW_MOOD

#define RGBLIGHT_LED_COUNT 1
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_MOOD
#define RGBLIGHT_DEFAULT_HUE 170
#define RGBLIGHT_DEFAULT_VAL 120
#define RGBLIGHT_LIMIT_VAL 150