BOOTMAGIC_ENABLE = yes
RGBLIGHT_ENABLE = yes
I2C_DRIVER_REQUIRED = yes
ENCODER_ENABLE = yes
AUDIO_ENABLE = no
AUDIO_DRIVER = pwm_hardware
BATTERY_ENABLE = yes
BATTERY_DRIVER = adc
ANALOG_DRIVER_REQUIRED = yes

WS2812_DRIVER_REQUIRED = yes
WS2812_DRIVER = vendor
